FROM adoptopenjdk/openjdk11:alpine-jre
ARG JAR_FILE=target/*.jar
WORKDIR /opt/app
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD
ENV DATASOURCE_USERNAME $DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD $DATASOURCE_PASSWORD
RUN echo DATASOURCE_USERNAME $DATASOURCE_USERNAME
RUN echo DATASOURCE_PASSWORD $DATASOURCE_PASSWORD
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]