server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2400024
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  redis:
    url: redis://127.0.0.1:6379

  web:
    resources:
      static-locations: classpath:/spring-frontend/

  thymeleaf:
    prefix: classpath:/spring-frontend/

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  messages:
    basename: lang.messages

upload:
  path: src/main/resources/img

download:
  path: src/main/resources/book-files

jwt:
  key: t911ur00
