server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie


spring:
  jpa:
    database: POSTGRESQL
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2400024
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  redis:
    url: redis://127.0.0.1:6379

  web:
    resources:
      static-locations: classpath:/spring-frontend/

  thymeleaf:
    prefix: classpath:/spring-frontend/

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  messages:
    basename: lang.messages

  security:
    oauth2:
      client:
        registration:
          vk:
            client-id: 51411687
            client-secret: x38uaMtZ89FSSDBoPf91
            redirect-uri: http://localhost:8085/login/oauth2/code/vk
            client-authentication-method: post
            scope: email
            authorization-grant-type: authorization_code
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            tokenUri: https://oauth.vk.com/access_token
            userInfoUri: https://api.vk.com/method/users.get?v=5.131
            userNameAttribute: id

upload:
  path: src/main/resources/img/

crm:
  url: localhost:4200/

download:
  path: src/main/resources/book-files

jwt:
  key: t911ur00

geolocation:
  key: 091c97ed150c464cb621c284a49e954f

sms:
  ru:
    url: https://sms.ru/code/call?api_id=
    apiId: 01AD529F-6C73-B85F-EBAF-7B0A709E8900
